# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 11:37
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('complete', '0002_auto_20170602_2001'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
